- name: pkg:seedcord
  color: 16a34a
  description: Changes related to the seedcord package
- name: pkg:mock
  color: 16a34a
  description: Changes related to the mock package
- name: pkg:services
  color: 16a34a
  description: Changes related to shared services
- name: pkg:plugins
  color: 16a34a
  description: Changes related to plugins
- name: pkg:types
  color: 16a34a
  description: Changes related to shared types
- name: pkg:utils
  color: 16a34a
  description: Changes related to utilities
- name: pkg:eslint-config
  color: 16a34a
  description: Changes related to ESLint config package
- name: pkg:tsconfig
  color: 16a34a
  description: Changes related to TSConfig package
- name: pkg:tsup-config
  color: 16a34a
  description: Changes related to TSUP config package
- name: area:docs
  color: 0e8a16
  description: Documentation updates
- name: area:tests
  color: fbca04
  description: Test updates
- name: area:ci
  color: 1d76db
  description: Continuous integration and automation changes
- name: area:config
  color: c5def5
  description: Repository configuration updates
- name: area:release
  color: d4c5f9
  description: Release engineering changes
- name: area:assets
  color: fcdc00
  description: Static asset updates
- name: type:bug
  color: d73a4a
  description: Bug fix
- name: type:feature
  color: a2eeef
  description: New feature or enhancement
- name: type:chore
  color: e4e669
  description: Maintenance tasks
- name: type:refactor
  color: cfd3d7
  description: Refactoring work
- name: type:docs
  color: 0e8a16
  description: Documentation only changes
- name: priority:high
  color: b60205
  description: Needs urgent attention
- name: priority:medium
  color: d93f0b
  description: Address in the near future
- name: priority:low
  color: fbca04
  description: Nice to have changes
- name: status:needs-triage
  color: d4c5f9
  description: Awaiting triage
- name: status:blocked
  color: b60205
  description: Blocked by another task or dependency
- name: good first issue
  color: 7057ff
  description: Great for newcomers to the project
