- name: pkg:seedcord
  color: ff6b6b
  description: Changes related to the seedcord package
- name: pkg:mock
  color: 8d6e63
  description: Changes related to the mock package
- name: pkg:services
  color: 45b7d1
  description: Changes related to shared services
- name: pkg:plugins
  color: 02796b
  description: Changes related to plugins
- name: pkg:types
  color: ffeaa7
  description: Changes related to shared types
- name: pkg:utils
  color: dda0dd
  description: Changes related to utilities
- name: pkg:eslint-config
  color: 78597d
  description: Changes related to ESLint config package
- name: pkg:tsconfig
  color: 196699
  description: Changes related to TSConfig package
- name: pkg:tsup-config
  color: 196699
  description: Changes related to TSUP config package
- name: pkg:api-docs
  color: 85c1e9
  description: Changes related to API docs tooling
- name: pkg:doc-engine
  color: 9b59b6
  description: Changes related to the documentation engine package
- name: area:docs
  color: 28a745
  description: Documentation updates
- name: area:tests
  color: ffc107
  description: Test updates
- name: area:ci
  color: 007bff
  description: Continuous integration and automation changes
- name: area:config
  color: 6c757d
  description: Repository configuration updates
- name: area:release
  color: e83e8c
  description: Release engineering changes
- name: area:assets
  color: fd7e14
  description: Static asset updates
- name: type:bug
  color: dc3545
  description: Bug fix
- name: type:feature
  color: 17a2b8
  description: New feature or enhancement
- name: type:chore
  color: ffc107
  description: Maintenance tasks
- name: type:refactor
  color: 6c757d
  description: Refactoring work
- name: type:docs
  color: 28a745
  description: Documentation only changes
- name: priority:high
  color: dc3545
  description: Needs urgent attention
- name: priority:medium
  color: fd7e14
  description: Address in the near future
- name: priority:low
  color: ffc107
  description: Nice to have changes
- name: status:needs-triage
  color: 6f42c1
  description: Awaiting triage
- name: status:blocked
  color: dc3545
  description: Blocked by another task or dependency
- name: good first issue
  color: 28a745
  description: Great for newcomers to the project
