# Use an official Node.js runtime as the base image
FROM node:20.12.2

# Set the working directory in the Docker image
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package.json ./

# Install the project dependencies
RUN npm install

# Copy the rest of the project files to the working directory
COPY . .

# Compile the TypeScript code
RUN npm run build

# Define the command to run the app
CMD [ "npm", "run", "start:prod" ]