packages:
    - packages/*

catalogs:
    deps:
        chalk: 5.6.2
        discord.js: 14.23.2
        envapt: 4.0.0
        mongoose: 8.19.1
        reflect-metadata: 0.2.2
    peer:
        eslint: 9.37.0
        typescript: 5.9.3
