packages:
  - packages/*

catalogs:
  peer:
    typescript: 5.9.2
    eslint: 9.36.0
  deps:
    chalk: 5.6.2
    discord.js: 14.22.1
    mongoose: 8.18.3
    envapt: 3.0.2
    reflect-metadata: 0.2.2
