packages:
  - packages/*

catalogs:
  deps:
    chalk: 5.6.2
    discord.js: 14.22.1
    envapt: 3.0.2
    mongoose: 8.18.3
    reflect-metadata: 0.2.2
  peer:
    eslint: 9.36.0
    typescript: 5.9.3
