packages:
- packages/*

catalogs:
  peer:
    typescript: ^5.9.2
    eslint: ^9.33.0
  deps:
    chalk: ^5.6.0
    discord.js: ^14.22.1
    mongoose: ^8.18.0
    envapt: ^2.2.9
    reflect-metadata: ^0.2.2
