name: Turbo cache setup
description: Export TURBO_* env and restore .turbo cache
inputs:
    turbo_token:
        description: Turborepo remote cache token
        required: false
    turbo_team:
        description: Turborepo team slug
        required: false
    enable_fallback_cache:
        description: Use actions/cache for .turbo as a fallback
        required: false
        default: 'true'

runs:
    using: composite
    steps:
        - name: Export TURBO env
          shell: bash
          run: |
              if [ -n "${{ inputs.turbo_token }}" ]; then
                echo "TURBO_TOKEN=${{ inputs.turbo_token }}" >> "$GITHUB_ENV"
              fi
              if [ -n "${{ inputs.turbo_team }}" ]; then
                echo "TURBO_TEAM=${{ inputs.turbo_team }}" >> "$GITHUB_ENV"
              fi

        - name: Check remote cache configuration
          shell: bash
          run: |
              if [ -n "${TURBO_TOKEN:-}" ] && [ -n "${TURBO_TEAM:-}" ]; then
                echo "Remote cache configured"
              else
                echo "No remote cache detected. Will rely on local cache if enabled."
              fi

        - name: Restore turbo cache fallback
          if: ${{ inputs.enable_fallback_cache == 'true' }}
          uses: actions/cache@v4
          with:
              path: .turbo
              key: ${{ runner.os }}-turbo-${{ github.sha }}
              restore-keys: |
                  ${{ runner.os }}-turbo-
