import { SeedcordErrorCode } from './ErrorCodes';
import { paint } from './palette';

/** @internal */
const messages = {
    [SeedcordErrorCode.ConfigMissingEnv]: (name: string) => `Missing ${name} environment variable.`,
    [SeedcordErrorCode.ConfigInvalidEnv]: (name: string, expected?: string) =>
        expected ? `Invalid ${name} value. Expected ${expected}.` : `Invalid ${name} value.`,
    [SeedcordErrorCode.ConfigManifestNotGenerated]: () =>
        'The route manifest is generated by `seedcord build`. Run the build before importing it.',
    [SeedcordErrorCode.ConfigWebhookUrlInvalid]: (envKey: string) =>
        `${envKey} is not a well-formed Discord webhook url.`,
    [SeedcordErrorCode.ConfigWebhookNotFound]: (envKey: string) =>
        `The webhook behind ${envKey} does not exist on Discord.`,
    [SeedcordErrorCode.ConfigEmojiUnresolved]: (count: number, failures: string) =>
        `Could not resolve ${count} configured emoji${count === 1 ? '' : 's'} at startup.\n${failures}`,
    [SeedcordErrorCode.ConfigTokenUnreadable]: () =>
        "DISCORD_BOT_TOKEN carries no readable application id. Discord builds the first part of a bot token from that id, so a token failing here is truncated or mistyped. Copy it again from your application's Bot page.",
    [SeedcordErrorCode.MissingGuildsIntent]: (commands: string) =>
        `Add GatewayIntentBits.Guilds to clientOptions.intents. Without it discord.js doesn't cache any guild, so interaction.guild is null inside these commands: ${commands}.`,
    [SeedcordErrorCode.UnsupportedNodeVersion]: (required: string, running: string) =>
        `seedcord requires Node ${required} and this process runs ${running}. Upgrade Node before starting the bot.`,

    [SeedcordErrorCode.LifecycleAddAfterCompletion]: () =>
        'Cannot add tasks after startup sequence has already completed.',
    [SeedcordErrorCode.LifecycleAddDuringRun]: () => 'Cannot add tasks while startup sequence is in progress.',
    [SeedcordErrorCode.LifecycleRemoveDuringRun]: () => 'Cannot remove tasks while startup sequence is in progress.',
    [SeedcordErrorCode.LifecycleUnknownPhase]: (phase: unknown) => `Unknown phase: ${String(phase)}.`,
    [SeedcordErrorCode.LifecyclePhaseFailures]: (phase: string, failures: number) =>
        `Phase ${phase} completed with ${failures} failed task${failures === 1 ? '' : 's'}.`,
    [SeedcordErrorCode.LifecycleTaskTimeout]: (taskName: string, timeout: number) =>
        `Task "${taskName}" timed out after ${timeout}ms.`,
    [SeedcordErrorCode.LifecycleRestartAfterFailure]: () =>
        'Startup failed and this host cannot start again. Construct a new instance.',
    [SeedcordErrorCode.LifecycleInvalidShutdownDeadline]: (declared: number) =>
        `lifecycle.shutdownDeadline is ${declared}. Pass a positive number of milliseconds, or omit it for the default.`,

    [SeedcordErrorCode.CoreSingletonViolation]: () =>
        'Seedcord can only be instantiated once. Use the existing instance instead.',
    [SeedcordErrorCode.CorePluginAfterInit]: () => 'Cannot attach a plugin after initialization.',
    [SeedcordErrorCode.CorePluginKeyExists]: (key: string) => `Plugin with key "${key}" already exists.`,
    [SeedcordErrorCode.CoreBotRoleMissing]: (guildId?: string) =>
        guildId ? `Bot role not found in guild ${guildId}.` : 'Bot role not found in guild.',
    [SeedcordErrorCode.CoreControllerPathMissing]: (controllerName: string, pathKind: string) =>
        `${controllerName} was instantiated without a ${pathKind} path.`,
    [SeedcordErrorCode.CoreDirectoryImportFailed]: (file: string) => `${file} threw while importing.`,
    [SeedcordErrorCode.CoreDirectoryUnreadable]: (dir: string) => `${dir} could not be read.`,
    [SeedcordErrorCode.CorePluginReservedChannel]: (key: string) =>
        `Plugin key "${key}" is a channel the framework logs on. Pick another key.`,
    [SeedcordErrorCode.CoreApplicationUnavailable]: () =>
        "The bot's application id resolves during startup. You read it before that. Read it inside a handler, inside a plugin's ready(), or after start() resolves.",
    [SeedcordErrorCode.CoreAccessorUnresolved]: (accessor: string, key: string) =>
        `${accessor}.${key} has no value yet. ${accessor} fills during startup, and a read at the top of a file runs before that.`,
    [SeedcordErrorCode.CoreLifecycleUnavailable]: (accessor: string) =>
        `core.${accessor}.addTask() does not work here. This bot was built with createSeedcord() whose build never runs startup or shutdown. Your task would never run. Do the work inside your handler instead. To use startup and shutdown, run the bot on node with new Seedcord(config).start().`,
    [SeedcordErrorCode.CoreBusEmitUnavailable]: (event: string) =>
        `core.bus.emit('${event}') would reach your on() listeners and skip every Subscriber class. Call core.bus.publish('${event}', data) to run both.`,

    [SeedcordErrorCode.DecoratorCommandAlreadyRegistered]: (
        commandName: string,
        existingScope: string,
        requestedScope: string
    ) =>
        `Command "${commandName}" is already registered as a "${existingScope}" command and cannot be re-registered as a "${requestedScope}" command.`,
    [SeedcordErrorCode.DecoratorCommandGlobalWithGuilds]: () =>
        'RegisterCommand("global") cannot have guilds specified.',
    [SeedcordErrorCode.DecoratorCommandGuildWithoutGuilds]: () =>
        'RegisterCommand("guild") requires a non-empty guilds array.',
    [SeedcordErrorCode.DecoratorInvalidMiddlewarePriority]: () => 'Middleware priority must be a finite number.',
    [SeedcordErrorCode.DecoratorWebhookUrlMissing]: (className: string) =>
        `${className} extends WebhookLog and needs a @WebhookUrl decorator naming its env var.`,

    [SeedcordErrorCode.DecoratorEmptyMiddlewareFilter]: (key: string) =>
        `\`${key}\` was given an empty array. Drop the key to run the middleware on everything.`,
    [SeedcordErrorCode.InteractionDuplicateRoute]: (route: string, first: string, second: string) =>
        `Two interaction handlers resolve to the same route \`${route}\`. Registered by ${first} and ${second}. Rename one.`,
    [SeedcordErrorCode.DuplicateMiddleware]: (name: string) =>
        `Two different middleware classes share the name \`${name}\`. Rename one so they do not collide.`,
    [SeedcordErrorCode.ManifestEntryWrongClass]: (array: string, className: string, base: string) =>
        `The manifest lists \`${className}\` under \`${array}\`, but \`${className}\` doesn't extend ${base}. Move it to the array for its own base, or drop it.`,

    [SeedcordErrorCode.ReplyIllegalAckState]: (method: string, reason: string, alternative: string, routeId: string) =>
        `${paint.sky(`${method}()`)} was called when ${reason}.\n${alternative} (route ${paint.mute(routeId)})`,
    [SeedcordErrorCode.ReplyComponentSerialization]: (
        componentClass: string,
        index: number,
        detail: string,
        routeId: string
    ) =>
        `${paint.sky(componentClass)} at components[${index}] failed to serialize: ${detail.replace(/\.$/, '')}. (route ${paint.mute(routeId)})`,
    [SeedcordErrorCode.ReplyForeignEditTarget]: (method: string, targetId: string, routeId: string) =>
        `${paint.sky(`${method}()`)} was passed message ${targetId}, which this interaction did not send.\nPass a message this interaction sent, returned by reply(), followUp(), edit(), or update(). (route ${paint.mute(routeId)})`,
    [SeedcordErrorCode.ReplyUpdateWithoutSource]: (method: string, routeId: string) =>
        `${paint.sky(`${method}()`)} was called on a modal opened from a command, which has no source message.\nUse reply() or defer() instead. (route ${paint.mute(routeId)})`,
    [SeedcordErrorCode.ReplyCallbackMissingMessage]: (method: string, routeId: string) =>
        `The interaction callback for ${paint.sky(`${method}()`)} returned no message. (route ${paint.mute(routeId)})`,

    [SeedcordErrorCode.CustomIdInvalidPrefix]: (prefix: string) =>
        `customId prefix ${JSON.stringify(prefix)} must be a non-empty string without a colon or control character.`,
    [SeedcordErrorCode.CustomIdReservedFieldName]: (field: string) =>
        `customId field name ${JSON.stringify(field)} is integer-like, which JS reorders. Use a non-numeric name.`,
    [SeedcordErrorCode.CustomIdEmptyChoices]: (field: string, method: string) =>
        `customId field ${JSON.stringify(field)} uses ${method}() with no choices. Make the field nullable or provide at least one choice.`,
    [SeedcordErrorCode.CustomIdInvalidBounds]: (field: string, min: number, max: number) =>
        `customId field ${JSON.stringify(field)} has min ${min} greater than max ${max}.`,
    [SeedcordErrorCode.CustomIdValueRejected]: (field: string, expected: string, value: string) =>
        `customId field ${JSON.stringify(field)} expects ${expected}, got ${value}.`,
    [SeedcordErrorCode.CustomIdWireTooLong]: (length: number) =>
        `Encoded customId is ${length} characters, Discord allows at most 100.`,
    [SeedcordErrorCode.CustomIdDuplicateFieldName]: (field: string) =>
        `customId field ${JSON.stringify(field)} is already defined in this chain.`,
    [SeedcordErrorCode.CustomIdHandlerRouteMissing]: (className: string) =>
        `${className} is missing its route decorator. Add the one that matches its base, for example @ButtonRoute or @UserMenuRoute.`,
    [SeedcordErrorCode.CustomIdMatchArmMissing]: (prefix: string) =>
        `match() has no arm for the decoded route ${JSON.stringify(prefix)}.`,
    [SeedcordErrorCode.CustomIdWireStale]: (prefix: string) =>
        `customId ${JSON.stringify(prefix)} was minted under an older shape of this definition. Adding, removing, changing, or moving a field changes the layout hash.`,
    [SeedcordErrorCode.CustomIdWireInvalid]: (detail: string) => `customId could not be decoded. ${detail}.`,
    [SeedcordErrorCode.SlashMatchArmMissing]: (route: string) =>
        `match() has no arm for the command route ${JSON.stringify(route)}.`,
    [SeedcordErrorCode.AutocompleteMatchArmMissing]: (field: string) =>
        `match() has no arm for the focused field ${JSON.stringify(field)}.`,
    [SeedcordErrorCode.EventMatchArmMissing]: (event: string) =>
        `match() has no arm for the event ${JSON.stringify(event)}.`,
    [SeedcordErrorCode.ContextMenuMatchArmMissing]: (name: string) =>
        `match() has no arm for the context menu command ${JSON.stringify(name)}.`,
    [SeedcordErrorCode.EventMiddlewareNameUnavailable]: () =>
        `this.eventName is only available on middleware the controller constructed with a fired event name.`,
    [SeedcordErrorCode.AutocompleteNoFocusedOption]: () => `Autocomplete payload has no focused option.`,
    [SeedcordErrorCode.ModalFieldNotFound]: (customId: string) =>
        `The submitted modal carries no field with the custom id ${JSON.stringify(customId)}. Check it against the id you gave the component when you built the modal.`,
    [SeedcordErrorCode.ModalFieldWrongKind]: (customId: string, kind: string, getter?: string) =>
        getter
            ? `Modal field ${JSON.stringify(customId)} holds ${kind}. Read it with ${getter}().`
            : `Modal field ${JSON.stringify(customId)} holds ${kind}. No getter reads that kind.`,
    [SeedcordErrorCode.ModalFieldEmpty]: (customId: string) =>
        `Modal field ${JSON.stringify(customId)} carries no selection. Build the component as required, or read it without the required argument.`,
    [SeedcordErrorCode.ModalFieldChannelType]: (customId: string, picked: string, allowed: string) =>
        `Modal field ${JSON.stringify(customId)} picked a ${picked} channel. This read allows ${allowed}.`,
    [SeedcordErrorCode.DispatchStateMissing]: (key: string) =>
        `Nothing set \`${key}\` on this dispatch. Check that the middleware writing it is registered and that its filter covers this dispatch.`,

    [SeedcordErrorCode.GateInvalidCooldownDuration]: (input: string) =>
        `Cooldown duration ${JSON.stringify(input)} is not valid. Pass a number of seconds or a duration string like '30m', '24h', or '500ms'.`,

    [SeedcordErrorCode.PaginationInvalidPerPage]: (perPage: number) =>
        `perPage must be a positive integer, got ${perPage}.`,
    [SeedcordErrorCode.PaginationTooManyControls]: (count: number) =>
        `A control row holds at most 5 buttons, got ${count}.`,
    [SeedcordErrorCode.PaginationEmptyControls]: () => `A control row must hold at least one control.`,
    [SeedcordErrorCode.PaginationDuplicateControls]: (key: string) =>
        `A control row cannot repeat the '${key}' control.`,

    [SeedcordErrorCode.ColorUnresolvable]: (value: string) => `Cannot convert ${value} into a color.`,
    [SeedcordErrorCode.ColorOutOfRange]: () => 'Color must be within the range 0 to 16777215 (0xffffff).',

    [SeedcordErrorCode.PluginOptionsRejected]: (pluginName: string, reason: string) =>
        `${pluginName} rejected its options, ${reason.replace(/\.$/, '')}.`,
    [SeedcordErrorCode.PluginDisposeFailures]: (count: number) => `${count} plugins failed to dispose.`,
    [SeedcordErrorCode.PluginInvalidLifecycleTimeout]: (pluginName: string, field: string, declared: number) =>
        `${pluginName} declared lifecycle ${field}.timeout as ${declared}. Pass a positive number of milliseconds, or omit it for the default.`,

    [SeedcordErrorCode.PluginMongooseServiceDecoratorMissing]: (className: string) =>
        `Missing @RegisterMongooseService on ${className}.`,
    [SeedcordErrorCode.PluginMongooseConnectionFailed]: (databaseName?: string) =>
        databaseName ? `Could not connect to MongoDB (${databaseName}).` : 'Could not connect to MongoDB.',
    [SeedcordErrorCode.PluginMongooseDisconnectFailed]: () =>
        'Failed to disconnect from MongoDB cleanly during shutdown.',
    [SeedcordErrorCode.PluginMongooseServicesNotReady]: () =>
        'Mongoose services accessed before the plugin finished initializing.',
    [SeedcordErrorCode.PluginMongooseModelCreationFailed]: (modelName: string, className: string) =>
        `Could not build the mongoose model ${modelName} for ${className}.`,
    [SeedcordErrorCode.PluginMongooseModelNameMissing]: (className: string) =>
        `Empty model name on ${className}. Provide a non-empty modelName via @RegisterMongooseService().`,

    [SeedcordErrorCode.PluginKyselyServiceDecoratorMissing]: (className: string) =>
        `Missing @RegisterKyselyService on ${className}.`,
    [SeedcordErrorCode.PluginKyselyServiceTableMissing]: (className: string) =>
        `Missing table metadata for ${className}. Provide a table via @RegisterKyselyService().`,
    [SeedcordErrorCode.PluginKyselyInvalidStepCount]: () => 'Migration step count must be a non-negative integer.',
    [SeedcordErrorCode.PluginKyselyUnknownDirection]: (direction: unknown) =>
        `Unknown migration direction: ${String(direction)}.`,
    [SeedcordErrorCode.PluginKyselyUnresolvedMigrationsPath]: (label: string) =>
        `Unable to resolve migrations at path: ${label}.`,
    [SeedcordErrorCode.PluginKyselyNoMigrationFiles]: () => 'No migration files provided.',
    [SeedcordErrorCode.PluginKyselyInvalidMigrationModule]: (filePath: string) =>
        `Migration file ${filePath} must export async functions up and down.`,
    [SeedcordErrorCode.PluginKyselyNonErrorFailure]: (message: string) => `Migration failure: ${message}.`,
    [SeedcordErrorCode.PluginKyselyDisconnectFailed]: () =>
        'Failed to close the Postgres pool cleanly during shutdown.',
    [SeedcordErrorCode.PluginKyselyServicesNotReady]: () =>
        'Kysely services accessed before the plugin finished initializing.',
    [SeedcordErrorCode.PluginKyselyConnectionFailed]: (databaseName?: string) =>
        databaseName ? `Could not connect to Postgres (${databaseName}).` : 'Could not connect to Postgres.',
    [SeedcordErrorCode.PluginKyselyBootstrapFailed]: (databaseName: string) =>
        `Failed to ensure database ${databaseName} exists.`,

    [SeedcordErrorCode.CliConfigInvalidExport]: () => 'Config file must default export an object.',
    [SeedcordErrorCode.CliConfigMissingInstance]: () =>
        'Config must include an `instance` string that points to your Seedcord default export.',
    [SeedcordErrorCode.CliConfigNotFound]: (baseDir: string, candidates: readonly string[]) =>
        `Unable to locate a Seedcord config in ${baseDir}. Searched for ${candidates.join(', ')}.`,
    [SeedcordErrorCode.CliConfigMissingEntry]: () =>
        'Config must include an `entry` string that points to your startup script.',
    [SeedcordErrorCode.CliConfigEntryOutsideRoot]: (entryPath: string, root: string) =>
        `Entry file ${entryPath} must reside inside configured root ${root}.`,
    [SeedcordErrorCode.CliEntryNotFound]: (entryPath: string) => `Cannot find entry file at ${entryPath}.`,
    [SeedcordErrorCode.CliTsxImportFailed]: (entryPath: string, reason: string) =>
        `Failed to import ${entryPath} via tsx: ${reason}`,
    [SeedcordErrorCode.CliImportFailed]: (entryPath: string, nativeReason: string, fallbackReason: string) =>
        `Failed to import ${entryPath}: ${nativeReason} (the jiti fallback also failed: ${fallbackReason})`,
    [SeedcordErrorCode.CliInstanceInvalid]: () =>
        'Seedcord instance must default export an object with a start() method.',
    [SeedcordErrorCode.CliStartFailed]: (instancePath: string, reason: string) =>
        `Failed to start Seedcord from ${instancePath}: ${reason}`,
    [SeedcordErrorCode.CliBuildTsconfigNotFound]: (hint: string) =>
        `Unable to resolve a tsconfig for builds (${hint}). Provide build.tsconfig or add tsconfig.build.json / tsconfig.json.`,
    [SeedcordErrorCode.CliBuildFailed]: (diagnostics: string) => `TypeScript build failed:\n${diagnostics}`,
    [SeedcordErrorCode.CliBootstrapWriteFailed]: (targetPath: string, reason: string) =>
        `Failed to write bootstrap file at ${targetPath}: ${reason}`,
    [SeedcordErrorCode.CliCodegenDuplicateRoute]: (route: string, firstFile: string, secondFile: string) =>
        `Two commands resolve to the same slash route \`${route}\`. Defined in ${firstFile} and ${secondFile}. Rename one.`,
    [SeedcordErrorCode.CliCodegenCommandsDirUnreadable]: (dir: string, reason: string) =>
        `Could not read the commands directory ${dir} during codegen. ${reason}`,
    [SeedcordErrorCode.CliCodegenCommandConstructorThrew]: (name: string, file: string, reason: string) =>
        `${name} threw while codegen constructed it. Fix its constructor in ${file}. ${reason}`,
    [SeedcordErrorCode.CliCodegenDuplicateContextMenu]: (
        kind: string,
        name: string,
        firstFile: string,
        secondFile: string
    ) =>
        `Two ${kind} context-menu commands share the name \`${name}\`. Defined in ${firstFile} and ${secondFile}. Rename one.`,
    [SeedcordErrorCode.CliCleanAppFetchFailed]: (reason: string) =>
        `Could not resolve the application from the bot token. ${reason}`,
    [SeedcordErrorCode.CliCleanNoGuilds]: () =>
        'No guilds given. Pass --guild <ids...> or --all-guilds. Global commands are never touched.',
    [SeedcordErrorCode.CliCleanPurgeAllGuilds]: () =>
        '--purge cannot be combined with --all-guilds. Use --guild <ids> to purge specific guilds.',
    [SeedcordErrorCode.CliCancelled]: () => 'Cancelled.',
    [SeedcordErrorCode.CliCleanLargeBotUnconfirmed]: (count: number) =>
        `Refusing to scan ${count} guilds without confirmation. Re-run with --yes, or name specific guilds with --guild <ids>.`,
    [SeedcordErrorCode.CliCleanApplyNeedsYes]: () =>
        'Refusing to delete without confirmation in a non-interactive environment. Re-run with --yes.',
    [SeedcordErrorCode.CliTunnelUrlUnavailable]: (seconds: number) =>
        `cloudflared did not report a tunnel URL within ${seconds}s. Check that the binary runs and that the network allows it.`,
    [SeedcordErrorCode.CliTunnelNotVerified]: (url: string) => `Discord rejected ${url} as an interactions endpoint.`,
    [SeedcordErrorCode.CliTunnelUnreachable]: (url: string, seconds: number) =>
        `${url} did not answer within ${seconds}s, so nothing was PATCHed to Discord.`,
    [SeedcordErrorCode.CliConfigInvalidField]: (field: string, expected: string) =>
        `Config \`${field}\` must be ${expected} when provided.`,
    [SeedcordErrorCode.CreateCancelled]: () => 'Cancelled.',
    [SeedcordErrorCode.CreateFlagNotApplicable]: (flag: string) =>
        `The --${flag} flag does not apply to the answers you gave.`,
    [SeedcordErrorCode.CreateInvalidAnswer]: (flag: string, reason: string) => `--${flag}: ${reason}`,
    // node's parseArgs message ends on an unclosed quote
    [SeedcordErrorCode.CreateBadUsage]: (reason: string) => `${reason}\nRun with --help for the flag list.`,
    [SeedcordErrorCode.CreateTargetNotEmpty]: (target: string) =>
        `${target} already has files in it. Pick an empty directory or a name that does not exist yet.`,
    [SeedcordErrorCode.CreateStepFailed]: (command: string, reason: string) => `\`${command}\` failed.\n${reason}`
} satisfies Record<SeedcordErrorCode, (...args: never[]) => string>;

/** @internal */
export type SeedcordErrorArguments<Code extends SeedcordErrorCode> = Parameters<(typeof messages)[Code]>;

/** @internal */
export function formatSeedcordErrorMessage<Code extends SeedcordErrorCode>(
    code: Code,
    args?: SeedcordErrorArguments<Code>
): string {
    const formatter = messages[code];
    const resolvedArgs = (args ?? []) as unknown[];
    return (formatter as (...params: unknown[]) => string)(...resolvedArgs);
}
