import { ErrorUtils, ExecutableInteraction } from '../../../lib';

/**
 * Decorator function that catches errors thrown by the decorated method and sends an error response.
 * Error responses are generated by ErrorUtils, so users need to map their custom errors and relevant responses in '../../../lib/Errors/index.ts'.
 * If no mapping is found, a generic error response will be sent.
 */
export function Catchable() {
  return function (
    _target: ExecutableInteraction,
    _propertyKey: string,
    descriptor: TypedPropertyDescriptor<(...args: any[]) => Promise<void>>
  ) {
    const originalMethod = descriptor.value;

    descriptor.value = async function (
      this: ExecutableInteraction,
      ...args: any[]
    ): Promise<void> {
      const interaction = this.event;

      if (!originalMethod) {
        throw new Error('Method not found');
      }

      try {
        await originalMethod.apply(this, args);
      } catch (error) {
        const res = {
          embeds: [ErrorUtils.getErrorEmbed(error).getComponent],
          ephemeral: true
        };

        if (interaction.replied) {
          await interaction.followUp(res);
        } else if (interaction.deferred && interaction.isChatInputCommand()) {
          await interaction.editReply(res);
        } else {
          await interaction.followUp(res);
        }
      }
    };
  };
}
