name: Release metadata

description: Derives release title based on package count

outputs:
    title:
        description: PR title.
        value: ${{ steps.metadata.outputs.title }}

runs:
    using: composite
    steps:
        - id: metadata
          name: Compute release metadata
          shell: bash
          run: |
              set -euo pipefail

              OUTPUT=$(pnpm tsx scripts/release-metadata.ts)
              COUNT=$(printf '%s\n' "$OUTPUT" | grep '^count=' | head -n1 | cut -d'=' -f2-)

              TITLE="chore: releasing ${COUNT} packages"

              echo "title=$TITLE" >> "$GITHUB_OUTPUT"
