name: Release metadata

description: Derives release title and version based on package.json

outputs:
    version:
        description: Next version to be released. Empty if none.
        value: ${{ steps.metadata.outputs.version }}
    title:
        description: PR title.
        value: ${{ steps.metadata.outputs.title }}
    body:
        description: PR body describing released packages.
        value: ${{ steps.metadata.outputs.body }}

runs:
    using: composite
    steps:
        - id: metadata
          name: Compute release metadata
          shell: bash
          run: |
              set -euo pipefail

              OUTPUT=$(pnpm tsx scripts/release-metadata.ts)
              VERSION=$(printf '%s\n' "$OUTPUT" | grep '^version=' | head -n1 | cut -d'=' -f2-)
              TITLE=$(printf '%s\n' "$OUTPUT" | grep '^title=' | head -n1 | cut -d'=' -f2-)
              BODY_B64=$(printf '%s\n' "$OUTPUT" | grep '^body_b64=' | head -n1 | cut -d'=' -f2-)

              if [ -n "$BODY_B64" ]; then
                  BODY=$(printf '%s' "$BODY_B64" | base64 --decode)
              else
                  BODY=''
              fi

              {
                  echo "version=$VERSION"
                  echo "title=$TITLE"
                  if [ -n "$BODY" ]; then
                      printf 'body<<__EOF__\n%s\n__EOF__\n' "$BODY"
                  else
                      echo "body="
                  fi
              } >> "$GITHUB_OUTPUT"
